### ISSUE TITLE
custom increment & decrement value

### ISSUE THREAD

**Issue by guycalledseven** [liuggio/statsd-php-client#25]
Just out of curiosity, why haven't you implemented custom increment & decrement value?

Your method produceStatsdData in StatsdDataFactory can accept custom value parameter  but methods increment and decrement  force to be it by 1.

eg:

    public function count($key, $val)
    {
        return $this->produceStatsdData($key, $val, StatsdDataInterface::STATSD_METRIC_COUNT);
    }

**Comment by liuggio** [comment]
fixed I think...
