### ISSUE TITLE
Moving sampling rate handling to StatsdData

### ISSUE THREAD

**Issue by dav-m85** [liuggio/statsd-php-client#34]
Sample rate is currently managed at the ```StatsdClient``` level, which may be disturbing IMHO. Usage is that you need to set the sample rate with the ```send()``` method, sampling all the data passed.

If my dataset contains sampled and non sampled data, then I have to call ```send()``` twice or more.

It would better to handle it in the StatsdData like this:
```php
$data = new StatsdData();
$data->setSampleRate('0.1');
echo $data->getMessage(); // ....|....|@0.1
```

**Comment by liuggio** [comment]
it sounds good to me.

**Comment by dav-m85** [comment]
Cool, I should be able to put a Pull Request then.

**Comment by liuggio** [comment]
we should make a new version... would you like to be core dev of this with write access? add me on hangout we can talk about it

**Comment by dav-m85** [comment]
Well I managed to avoid BC break, but I added some logic within the StatsdClient, hope you'll be ok with that (StatsdClient now enforce the sampling).

https://github.com/liuggio/statsd-php-client/pull/35

Having write would be a great honor thanks :+1:

**Comment by liuggio** [comment]
merged
