### ISSUE TITLE
Uppercase in StatsdService class name in 1.0.13

### ISSUE THREAD

**Issue by petitchevalroux** [liuggio/statsd-php-client#39]
Hello,

Is it possible to create a new tagged version with the following fix ?

https://github.com/petitchevalroux/statsd-php-client/commit/9d864afbd918d385ed375490c8571b13da731773

I am unable to autoload this classe otherwise (case sensitive filesystem)

BTW thanks for your work ;-)

**Comment by liuggio** [comment]
thanks for reporting 
in order to do this 
@dav-m85  we should re-modify the bundle
:\

**Comment by dav-m85** [comment]
That's right, this line is not restrictive enough: https://github.com/liuggio/StatsDClientBundle/blob/master/composer.json#L20

My apologizes for not foreseeing that. I'll put up pull requests fixing that right now.

**Comment by petitchevalroux** [comment]
Ty to both of you for your quick reponse ;)
