### ISSUE TITLE
Introduced BC break

### ISSUE THREAD

**Issue by chmeldax** [liuggio/statsd-php-client#41]
Hi,

sadly, `StatsdDataFactoryInterface` is now not **backward compatible**, because it introduces **new methods to the interface**; therefore our custom classes implementing this interface now cannot be used. (the simply do not comply with new interface).

I believe introducing a BC-break should lead to introducing a **new major version** (according to the semantic versioning). Could you please release a **new major version** or could you drop `setPrefix` and `setSuffix` from the  `StatsdDataFactoryInterface`?

Thanks,
Jan

**Comment by liuggio** [comment]
I agree with you

**Comment by dav-m85** [comment]
@chmeldax You are right, I apologize for not foreseeing this (the feature was too cool). I tagged a new v1.0.16 that removes the BC break, and moved the feature in a separate branch feature/prefix_suffix that we will use later for creating a 2.0 release.

Thank you so much for pointing that BC break.

**Comment by rcrowe** [comment]
We were hit by the same issue & can confirm that this has now fixed it.

**Comment by chmeldax** [comment]
@dav-m85: Thanks for fixing this issue. Happy to use statsd-php-client again :)
