### ISSUE TITLE
setSampleRate hidden by interface

### ISSUE THREAD

**Issue by tgr** [liuggio/statsd-php-client#44]
`StatsdDataInterface` includes getters but not setters. For most of them is is not really problematic as the factory offers a way to set the field on instantiation, but that is not the case for sample rate. So the only way to set sampling rate per stats record is something like
```
$statsdDataFactory->increment('foo')->setSampleRate(0.01);
```
which will be flagged by static analyzers as the interface  documented as the return type of `increment` does not have that method.

**Comment by liuggio** [comment]
Interface on the model doesn't make any sense to me, I think for now we can remove it from the annotation

**Comment by liuggio** [comment]
@tgr thanks for reporting a PR will now follow.

**Comment by liuggio** [comment]
https://github.com/liuggio/statsd-php-client/pull/49 :)
