### ISSUE TITLE
Why has 7fab3b0 been reverted?

### ISSUE THREAD

**Issue by NinoFloris** [liuggio/statsd-php-client#51]
7fab3b0

Would love to have a prefix feature.
My logging classes should not concern themselves with the specific prefix used to send stats.
Now I should keep injecting details like this.

**Comment by liuggio** [comment]
@dav-m85  what do you think?

**Comment by dav-m85** [comment]
We had to revert it because it introduced BC break with StatsdDataFactoryInterface. I agree with you this feature is a damn good feature, we should definitely look into reintroducing it.

@NinoFloris Are you willing to submit a PR on this one ?
